### ISSUE TITLE
Install Cloud-Forms 4.5

### ISSUE THREAD

**Issue by vskvsk1** [jsimonelli/cfme-rhconsulting-scripts#147]
for educational purposes I setup CloudForms4.5. But I come across an obstacle - how do I can to install a package cfme-gemset
here is the listing
 /mnt/Data/repo/cfme-gemset-5.10.6.1-1.el7cf.src.rpm                       
Updating / installing...
   1:cfme-gemset-5.10.6.1-1.el7cf     ################################# [100%]
$ sudo rpm -ivh /mnt/Data/repo/cfme-5.10.6.1-1.el7cf.x86_64.rpm                                   
error: Failed dependencies:
	cfme-gemset = 5.10.6.1 is needed by cfme-5.10.6.1-1.el7cf.x86_64

Thank you

**Comment by jeffwarnica** [comment]
CloudForms is delivered and installed as an appliance. Installing from RPM is not a supported process; indeed, it is never done.

**Comment by vskvsk1** [comment]
That is, is deployed CF only as a fully equipped virtual machine?

**Comment by jeffwarnica** [comment]
That is correct. I believe even the upstream MiQ project ships images as a product. Installing CF/MIQ is really only used for system development purposes. Even for lab usage, everyone starts with an appliance.
